version: '3.8'
services:
    postgres:
        restart: always
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    scheduler:
        restart: always
        image: apache/airflow:2.3.4-python3.10
        command: scheduler
        # restart_policy:
        #     condition: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./files:/opt/airflow/files
    webserver:
        image: apache/airflow:2.3.4-python3.10
        entrypoint: ./scripts/entrypoint.sh
        # restart_policy:
        #     condition: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./files:/opt/airflow/files
        ports:
            - "8080:8080"